apiVersion: v2
name: backend
description: Backend Microservice
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
  - name: mysql
    version: 0.1.0
    enabled: true
    repository: "file://../mysql"
